#!/usr/bin/env bash
# PreToolUse hook for Edit/Write.
#
# Refuses to touch protected files unless an env override is set:
#   - .env (real secrets)
#   - drizzle-generated migration files (regenerate via db:generate instead)
#   - dist/, node_modules/, coverage/

set -euo pipefail

input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[[ -z "$file" ]] && exit 0

block() {
  printf 'Blocked write to protected path: %s\n' "$file" >&2
  printf '  reason: %s\n\n' "$1" >&2
  printf '  Set CLAUDE_ALLOW_PROTECTED_WRITE=1 in the environment if this is genuinely intended.\n' >&2
  exit 2
}

# Allow override.
if [[ "${CLAUDE_ALLOW_PROTECTED_WRITE:-0}" == "1" ]]; then
  exit 0
fi

case "$file" in
  *"/.env"|*"/.env.local"|*"/.env.production"|*"/.env.staging")
    block "this is a real env file — edit .env.example instead, then update your local .env manually"
    ;;
  */src/infrastructure/db/migrations/*.sql)
    block "migrations are generated by drizzle-kit — edit the schema and run pnpm db:generate"
    ;;
  */dist/*|*/node_modules/*|*/coverage/*)
    block "build artefact — do not edit"
    ;;
esac

exit 0
